name: Workflow
on:
  pull_request:
  issues:
      types: ['opened']

jobs:
  Greeting:
    name: Greeting Message for reporting First Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congratulations on making your first Issue! :confetti_ball: If you haven't already, check out our [Contributing Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) and [Issue Reporting Guidelines](https://github.com/PalisadoesFoundation/talawa/blob/master/issue-guidelines.md) to ensure that you are following our guidelines for contributing and making issues."

  Opened-issues:
    name: Labeling the created issue has unapproved
    runs-on: ubuntu-latest
    needs: Greeting
    steps:
      - uses: Renato66/auto-label@v2.2.0
        if: ${{ github.event.action == 'issues' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["unapproved"]'
  
  Linter:
    name: Checks if code formatting is done correctly
    runs-on: ubuntu-latest
    needs: Opened-issues
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter format --set-exit-if-changed .

  Count-lines-of-code:
    name: Total number of lines should not be more than 300
    needs: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./.github/workflows/countline.sh
      - run: ./.github/workflows/countline.sh 300