name: Count Lines 
on: [pull_request]

jobs:
  count-lines-of-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Making the Script File excutable
      - run: chmod +x ./.github/workflows/countline.py
      
      # Running the Script File with max no. of lines limit
      - run: ./.github/workflows/countline.py 300